try {
    a=12;b=12
    console.log(a+b)
} catch (err) {
    console.log("there was an error")
}